/// Flutter icons CustomIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData home = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData trophy = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData design_tool = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData presentation = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData conversation = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData diamond = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData certificate = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData training = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData duplicate = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData profiles = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData download = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData loupe = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData menu = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData information = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData add = const IconData(0xe80f, fontFamily: _kFontFam);
}
